# 선형 회귀

y = 2x_1 + 3x_2 -4

In [14]:
import torch

x_train = torch.FloatTensor([[1, 2],
                             [3, 2],
                             [3, 7],
                             [1, 1],
                             [1, 0]])

y_train = torch.FloatTensor([[4],
                             [8],
                             [23],
                             [1],
                             [-2]])

## 초기화
W: 가중치

b: 편향

lr(learning Rate): 학습률

질문:

torch.rand()가 뭐 하는 함수지? 그리고 왜 가중치는 2, 1이고 편향은 1, 1이지? 벡터와 스칼라인가?

In [15]:
W = torch.rand(2, 1)
b = torch.rand(1, 1)
lr = 0.01

print("W: \n", W)
print("b: \n", b)

W: 
 tensor([[0.8554],
        [0.0198]])
b: 
 tensor([[0.8660]])


# 반복 횟수 설정

In [16]:
for epoch in range(3001):
    W.requires_grad_(True)
    b.requires_grad_(True)

    hypothesis = torch.mm(x_train, W) + b
    cost = torch.mean((hypothesis - y_train)**2)

    cost.backward()
    with torch.no_grad() as grd:
        W = W - lr * W.grad
        b = b - lr * b.grad

    if epoch % 100 == 0:
        print( 'epoch: {}, cost: {:.6f}, W: {}, b: {}'.format(epoch, cost.item(), W.squeeze(), b))

    

epoch: 0, cost: 83.479477, W: tensor([1.1340, 0.6150]), b: tensor([[0.9529]])
epoch: 100, cost: 1.822360, W: tensor([0.5931, 3.1222]), b: tensor([[-1.1318]])
epoch: 200, cost: 0.870119, W: tensor([0.8452, 3.1940]), b: tensor([[-2.0449]])
epoch: 300, cost: 0.446318, W: tensor([1.1556, 3.1511]), b: tensor([[-2.6099]])
epoch: 400, cost: 0.229360, W: tensor([1.3928, 3.1097]), b: tensor([[-3.0047]])
epoch: 500, cost: 0.117872, W: tensor([1.5645, 3.0788]), b: tensor([[-3.2867]])
epoch: 600, cost: 0.060577, W: tensor([1.6878, 3.0565]), b: tensor([[-3.4886]])
epoch: 700, cost: 0.031132, W: tensor([1.7762, 3.0405]), b: tensor([[-3.6334]])
epoch: 800, cost: 0.015999, W: tensor([1.8395, 3.0290]), b: tensor([[-3.7372]])
epoch: 900, cost: 0.008222, W: tensor([1.8850, 3.0208]), b: tensor([[-3.8116]])
epoch: 1000, cost: 0.004226, W: tensor([1.9175, 3.0149]), b: tensor([[-3.8649]])
epoch: 1100, cost: 0.002172, W: tensor([1.9409, 3.0107]), b: tensor([[-3.9032]])
epoch: 1200, cost: 0.001116, W: tensor([

In [17]:
x_test = torch.FloatTensor([[5, 10]])
test_result = torch.mm(x_test, W) + b
print(test_result.item())

35.99983596801758


# Scikit-learn

In [1]:
from sklearn.linear_model import LinearRegression

x = [[1,2], [3,2], [3,7], [1,1], [1,0]]
y = [[4], [8], [23], [1], [-2]]

model = LinearRegression() # 모델 생성
model.fit(x, y)

print(model.coef_, model.intercept_)

[[2. 3.]] [-4.]


In [3]:
print(model.predict([[5, 10]]))

[[36.]]


In [1]:
import numpy as np

def linear_regression(X, y, lr=0.01, num_epochs=1000):
    """
    n차원의 입력 행렬 X와 출력 벡터 y에 대해 선형 회귀를 수행하는 함수.
    
    Parameters:
    X (numpy array): 입력 데이터 (샘플 수 x 특성 수)
    y (numpy array): 출력 데이터 (샘플 수 x 1)
    lr (float): 학습률 (learning rate), default = 0.01
    num_epochs (int): 학습 반복 횟수 (epoch), default = 1000
    
    Returns:
    W (numpy array): 학습된 가중치 (특성 수 x 1)
    b (float): 학습된 편향 (bias)
    """
    # 데이터 차원
    n_samples, n_features = X.shape
    
    # 가중치(W)와 편향(b) 초기화
    W = np.random.randn(n_features, 1)  # 특성 수에 맞는 가중치 초기화
    b = np.random.randn(1)              # 편향 초기화
    
    # 경사 하강법을 통한 학습 과정
    for epoch in range(num_epochs):
        # 예측값 계산 (XW + b)
        y_pred = np.dot(X, W) + b
        
        # 손실 함수 (MSE) 계산
        cost = np.mean((y_pred - y) ** 2)
        
        # 가중치(W)와 편향(b)에 대한 그래디언트 계산
        W_grad = (2 / n_samples) * np.dot(X.T, (y_pred - y))  # W에 대한 gradient
        b_grad = (2 / n_samples) * np.sum(y_pred - y)         # b에 대한 gradient
        
        # 가중치와 편향 업데이트
        W -= lr * W_grad
        b -= lr * b_grad
        
        # 100 에포크마다 비용 출력
        if epoch % 100 == 0:
            print(f'Epoch {epoch}, Cost: {cost:.6f}')
    
    return W, b

# 사용 예시

# 입력 데이터 (5개의 샘플, 3개의 특성)
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [2, 3, 4],
              [6, 7, 8]])

# 출력 데이터
y = np.array([[14],
              [32],
              [50],
              [20],
              [44]])

# 선형 회귀 수행
W, b = linear_regression(X, y, lr=0.001, num_epochs=1000)

# 결과 출력
print(f'Final Weights (W):\n{W}')
print(f'Final Bias (b): {b}')

# 새로운 데이터 예측
X_test = np.array([[3, 5, 7]])  # 새로운 입력 데이터
y_test_pred = np.dot(X_test, W) + b
print(f'Prediction for X_test: {y_test_pred}')


Epoch 0, Cost: 462.169452
Epoch 100, Cost: 0.314627
Epoch 200, Cost: 0.257291
Epoch 300, Cost: 0.210403
Epoch 400, Cost: 0.172060
Epoch 500, Cost: 0.140705
Epoch 600, Cost: 0.115063
Epoch 700, Cost: 0.094095
Epoch 800, Cost: 0.076947
Epoch 900, Cost: 0.062925
Final Weights (W):
[[1.82507301]
 [2.06552412]
 [2.20040963]]
Final Bias (b): [1.07803247]
Prediction for X_test: [[32.28373952]]
