In [11]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Datatype of x: ", x.dtype)
print('x = \n', x)
print()
print("Datatype of y: ", y.dtype)
print('y = \n', y)

Datatype of x:  torch.int64
x = 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Datatype of y:  torch.float32
y = 
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


크기와 랭크(차원) 확인하기

In [5]:
print("Size:", x.size())
print("Shape:", x.shape)
print("차원(랭크):", x.ndimension())

Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
차원(랭크): 2


In [7]:
x_ones = torch.ones_like(x)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]) 

Random Tensor: 
 tensor([[0.8841, 0.7273, 0.5030],
        [0.5902, 0.3539, 0.3347],
        [0.1443, 0.3150, 0.3523]]) 



In [8]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zero_tensor} \n")

Random Tensor: 
 tensor([[0.5437, 0.2796, 0.4858],
        [0.2648, 0.2567, 0.6508]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# 텐서 모양 바꾸기

In [15]:
x0 = torch.unsqueeze(x, 0)
x1 = torch.unsqueeze(x, 1)
x2 = torch.unsqueeze(x, 2)

print("x: \n", x)
print()

print("x0.shape: ", x0.shape)
print("x0 \n", x0)
print()

print("x1.shape: ", x1.shape)
print("x1 \n", x1)
print()

print("x2.shape: ", x2.shape)
print("x2 \n", x2)

x: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

x0.shape:  torch.Size([1, 3, 3])
x0 
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

x1.shape:  torch.Size([3, 1, 3])
x1 
 tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])

x2.shape:  torch.Size([3, 3, 1])
x2 
 tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])


Numpy식의 표준 인덱싱과 슬라이싱

In [17]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
