In [1]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[1, 2, 3], [4,1 5, 6], [7, 8, 9]])

print("Datatype of x: ", x.dtype)
print('x = \n', x)
print()
print("Datatype of y: ", y.dtype)
print('y = \n', y)

Datatype of x:  torch.int64
x = 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Datatype of y:  torch.float32
y = 
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


크기와 랭크(차원) 확인하기

In [2]:
print("Size:", x.size())
print("Shape:", x.shape)
print("차원(랭크):", x.ndimension())

Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
차원(랭크): 2


In [3]:
x_ones = torch.ones_like(x)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]) 

Random Tensor: 
 tensor([[0.4456, 0.4388, 0.5862],
        [0.0375, 0.8112, 0.9529],
        [0.4861, 0.3275, 0.3846]]) 



In [4]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zero_tensor} \n")

Random Tensor: 
 tensor([[0.1602, 0.7723, 0.0368],
        [0.0169, 0.1401, 0.7414]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# 텐서 모양 바꾸기

In [5]:
x0 = torch.unsqueeze(x, 0)
x1 = torch.unsqueeze(x, 1)
x2 = torch.unsqueeze(x, 2)

print("x: \n", x)
print()

print("x0.shape: ", x0.shape)
print("x0 \n", x0)
print()

print("x1.shape: ", x1.shape)
print("x1 \n", x1)
print()

print("x2.shape: ", x2.shape)
print("x2 \n", x2)

x: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

x0.shape:  torch.Size([1, 3, 3])
x0 
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

x1.shape:  torch.Size([3, 1, 3])
x1 
 tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])

x2.shape:  torch.Size([3, 3, 1])
x2 
 tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])


Numpy식의 표준 인덱싱과 슬라이싱

In [6]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


# 산술 연산(Arithmetic operations)

In [11]:
print("tensor: \n", tensor)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
print("y3: \n", y3)
print(torch.matmul(tensor, tensor.T, out=y3))

tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
y3: 
 tensor([[0.1311, 0.6703, 0.2884, 0.2544],
        [0.2936, 0.1606, 0.5219, 0.5183],
        [0.6530, 0.8574, 0.5490, 0.1536],
        [0.8774, 0.8437, 0.8889, 0.2286]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [12]:
# element wise product
z1= tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])