1. torch.randn(10, 20)과 torch.randn(20)을 행렬곱하여 10x1의 행렬 만들기
    - unsqueeze 사용
2. torch.ones(2, 1) 텐서를 활용해 [[2, 2], [2, 2]] Tesnsor 만들기
    - repeat 사용
3. torch.zeros(2, 1) 텐서를 활용해 [[1, 1], [1, 1]] Tensor 만들기
    - broadcasting 사용
4. torch.zeros(10, 10).fill_diagonal_(2)의 텐서, 대각선은 0 나머지는 1로 만들기
    - where 사용
5. .grad 5 발생
    - backward, 미분
6. ResNet, IMAGENET1K_V1 불러오기
7. VGG16 불러오기

In [1]:
import torch

In [3]:
a = torch.randn(10, 20)
b = torch.randn(20)
print(a@b.unsqueeze(-1))
(a@b.unsqueeze(-1)).shape

tensor([[-4.0768],
        [-4.6661],
        [-6.2522],
        [-1.0876],
        [-1.0183],
        [ 3.0558],
        [-1.6564],
        [ 0.5354],
        [ 1.6618],
        [ 7.0132]])


torch.Size([10, 1])

In [15]:
mat = torch.ones(2, 1)

mat.repeat(1,2) *2

tensor([[2., 2.],
        [2., 2.]])

In [17]:
mat = torch.zeros(2, 1)

mat + torch.ones(1, 2)

tensor([[1., 1.],
        [1., 1.]])

In [14]:
mat = torch.zeros(10, 10).fill_diagonal_(2)

torch.where(mat==2., 1, mat)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
w = torch.tensor(1.0, requires_grad=True)
a = w*5
a.backward()
print(w.grad) 

tensor(5.)


In [20]:
from torchvision.models import resnet18

net = resnet18(num_classes=1000, weights='IMAGENET1K_V1')

In [21]:
from torchvision.models import vgg16

net = vgg16(num_classes=1000)