In [2]:
import torch

1. torch.randn(10, 20)과 torch.randn(20)을 행렬곱하여 10x1의 행렬 만들기

In [3]:
a = torch.randn(10, 20)
b = torch.randn(20)
print((a @ b).unsqueeze(1).shape)



torch.Size([10, 1])


2. torch.ones(2, 1) 텐서를 활용해 [[2, 2], [2, 2]] Tesnsor 만들기

In [16]:
mat = torch.ones(2, 1)
print(mat.repeat(1, 2) * 2)



tensor([[2., 2.],
        [2., 2.]])


3. torch.zeros(2, 1) 텐서를 활용해 [[1, 1], [1, 1]] Tensor 만들기(using bradcast)

In [20]:
mat = torch.zeros(2, 1)
add_1 = torch.ones(1,2)
print(mat + add_1)


tensor([[1., 1.],
        [1., 1.]])


4. torch.zeros(10, 10).fill_diagonal_(2)의 텐서, 대각선은 0 나머지는 1로 만들기

In [44]:
mat = torch.zeros(10, 10).fill_diagonal_(2)
torch.where(mat==2., 1, mat)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

5. .grad 5 발생

In [28]:
w = torch.tensor(1.0, requires_grad=True)
h = w**5
h.backward()
print(w.grad) 

tensor(5.)


6. ResNet, IMAGENET1K_V1 불러오기

In [30]:
from torchvision.models import resnet18
import torch
import torch.nn as nn
import torch.nn.functional as F

net = resnet18(num_classes=10)
print(net)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  


7. VGG16 불러오기

In [31]:
from torchvision.models import vgg16

net = vgg16(num_classes=10)
print(net)

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1